// ═══════════════════════════════════════
// KANJI PRO — Story Data
// Each story contains structured token data for runtime rendering.
// Token types: k=kanji, p=particle, v=verb, a=adjective, pr=pronoun, punc=punctuation, plain=untagged
// ═══════════════════════════════════════

const STORIES = [
  {
    id: "kappa",
    kanji: "河童",
    title: "河童の伝説",
    sub: "The Legend of the Kappa",
    lvl: "N4",
    wm: "河童",
    color: "#4a9a6a",
    pages: [
      {
        sentences: [
          {
            text: "河童は日本の有名な妖怪です。",
            tokens: [
              { type: "k", text: "河童", reading: "かっぱ", meaning: "kappa" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "a", text: "有名な", reading: "ゆうめいな", meaning: "famous" },
              { type: "k", text: "妖怪", reading: "ようかい", meaning: "creature" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "川に住んでいて、体は緑色です。",
            tokens: [
              { type: "k", text: "川", reading: "かわ", meaning: "river" },
              { type: "p", text: "に", reading: "に", meaning: "in" },
              { type: "v", text: "住んでいて", reading: "すんでいて", meaning: "lives" },
              { type: "punc", text: "、" },
              { type: "k", text: "体", reading: "からだ", meaning: "body" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "a", text: "緑色", reading: "みどりいろ", meaning: "green" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "頭の上に皿があります。",
            tokens: [
              { type: "k", text: "頭", reading: "あたま", meaning: "head" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "上", reading: "うえ", meaning: "top" },
              { type: "p", text: "に", reading: "に", meaning: "on" },
              { type: "k", text: "皿", reading: "さら", meaning: "plate" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "あります", reading: "あります", meaning: "exists" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "The Kappa is a famous creature from Japan. It lives in rivers and its body is green. On top of its head there is a plate.",
        pt: "O Kappa é uma criatura famosa do Japão. Ele vive em rios e seu corpo é verde. No topo de sua cabeça há um prato.",
        es: "El Kappa es una criatura famosa de Japón. Vive en ríos y su cuerpo es verde. En la parte superior de su cabeza hay un plato.",
      },
      {
        sentences: [
          {
            text: "この水がなくなると、力がなくなります。",
            tokens: [
              { type: "plain", text: "この" },
              { type: "k", text: "水", reading: "みず", meaning: "water" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "なくなると", reading: "なくなると", meaning: "runs out" },
              { type: "punc", text: "、" },
              { type: "k", text: "力", reading: "ちから", meaning: "power" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "なくなります", reading: "なくなります", meaning: "disappears" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "もし河童に会ったら、お辞儀をしてください。",
            tokens: [
              { type: "plain", text: "もし " },
              { type: "k", text: "河童", reading: "かっぱ", meaning: "kappa" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "会ったら", reading: "あったら", meaning: "if you meet" },
              { type: "punc", text: "、" },
              { type: "k", text: "お辞儀", reading: "おじぎ", meaning: "bow" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "してください", reading: "してください", meaning: "please do" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "If this water runs out, it loses its strength. If you ever meet a Kappa, please bow to it.",
        pt: "Se essa água acabar, ele perde sua força. Se você encontrar um Kappa, por favor faça uma reverência.",
        es: "Si el agua se agota, pierde su fuerza. Si alguna vez te encuentras con un Kappa, por favor hazle una reverencia.",
      },
    ],
  },
  {
    id: "tanuki",
    kanji: "狸",
    title: "狸の化け術",
    sub: "The Tanuki's Shapeshifting",
    lvl: "N4",
    wm: "狸",
    color: "#c47a3a",
    pages: [
      {
        sentences: [
          {
            text: "狸は日本の昔話によく出てきます。",
            tokens: [
              { type: "k", text: "狸", reading: "たぬき", meaning: "tanuki" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "昔話", reading: "むかしばなし", meaning: "folktale" },
              { type: "p", text: "に", reading: "に", meaning: "in" },
              { type: "plain", text: " よく " },
              { type: "v", text: "出てきます", reading: "でてきます", meaning: "appears" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "化ける力を持っていて、人に化けます。",
            tokens: [
              { type: "k", text: "化ける", reading: "ばける", meaning: "shapeshift" },
              { type: "k", text: "力", reading: "ちから", meaning: "power" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "持っていて", reading: "もっていて", meaning: "has" },
              { type: "punc", text: "、" },
              { type: "p", text: "人", reading: "ひと", meaning: "person" },
              { type: "p", text: "に", reading: "に", meaning: "into" },
              { type: "v", text: "化けます", reading: "ばけます", meaning: "transforms" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "The Tanuki often appears in Japanese folktales. It has the power to shapeshift into a person.",
        pt: "O Tanuki aparece frequentemente nos contos populares japoneses. Ele tem o poder de se transformar em uma pessoa.",
        es: "El Tanuki aparece frecuentemente en los cuentos populares japoneses. Tiene el poder de transformarse en una persona.",
      },
      {
        sentences: [
          {
            text: "夜にお寺の坊主に化けて、人々を驚かせます。",
            tokens: [
              { type: "k", text: "夜", reading: "よる", meaning: "night" },
              { type: "p", text: "に", reading: "に", meaning: "at" },
              { type: "k", text: "お寺", reading: "おてら", meaning: "temple" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "坊主", reading: "ぼうず", meaning: "monk" },
              { type: "p", text: "に", reading: "に", meaning: "into" },
              { type: "v", text: "化けて", reading: "ばけて", meaning: "transforms" },
              { type: "punc", text: "、" },
              { type: "p", text: "人々", reading: "ひとびと", meaning: "people" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "驚かせます", reading: "おどろかせます", meaning: "surprises" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "でも、狸は幸せを持ってくる動物です。",
            tokens: [
              { type: "plain", text: "でも" },
              { type: "punc", text: "、" },
              { type: "k", text: "狸", reading: "たぬき", meaning: "tanuki" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "幸せ", reading: "しあわせ", meaning: "happiness" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "持ってくる", reading: "もってくる", meaning: "brings" },
              { type: "k", text: "動物", reading: "どうぶつ", meaning: "animal" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "At night, it transforms into a temple monk and surprises people. But the Tanuki brings happiness.",
        pt: "À noite, ele se transforma em um monge de templo e surpreende as pessoas. Mas o Tanuki traz felicidade.",
        es: "Por la noche, se transforma en un monje de templo y sorprende a la gente. Pero el Tanuki trae felicidad.",
      },
    ],
  },
  {
    id: "sakura",
    kanji: "桜",
    title: "桜の季節",
    sub: "Cherry Blossom Season",
    lvl: "N5",
    wm: "桜",
    color: "#d48ea0",
    pages: [
      {
        sentences: [
          {
            text: "春に日本で桜が咲きます。",
            tokens: [
              { type: "k", text: "春", reading: "はる", meaning: "spring" },
              { type: "p", text: "に", reading: "に", meaning: "in" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "k", text: "桜", reading: "さくら", meaning: "cherry blossom" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "咲きます", reading: "さきます", meaning: "blooms" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "みんなは公園に行って、花見をします。",
            tokens: [
              { type: "p", text: "みんな", reading: "みんな", meaning: "everyone" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "公園", reading: "こうえん", meaning: "park" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "行って", reading: "いって", meaning: "goes" },
              { type: "punc", text: "、" },
              { type: "k", text: "花見", reading: "はなみ", meaning: "flower viewing" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "します", reading: "します", meaning: "does" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "桜はとてもきれいです。",
            tokens: [
              { type: "k", text: "桜", reading: "さくら", meaning: "cherry blossom" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "plain", text: " とても " },
              { type: "a", text: "きれい", reading: "きれい", meaning: "beautiful" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "In spring, cherry blossoms bloom in Japan. Everyone goes to the park for hanami. They are very beautiful.",
        pt: "Na primavera, as cerejeiras florescem no Japão. Todos vão ao parque para o hanami. Elas são muito bonitas.",
        es: "En primavera, los cerezos florecen en Japón. Todos van al parque para el hanami. Son muy hermosos.",
      },
    ],
  },
  {
    id: "onsen",
    kanji: "温泉",
    title: "温泉の旅",
    sub: "A Hot Spring Trip",
    lvl: "N4",
    wm: "湯",
    color: "#6aace0",
    pages: [
      {
        sentences: [
          {
            text: "私たちは週末に温泉に行きました。",
            tokens: [
              { type: "p", text: "私たち", reading: "わたしたち", meaning: "we" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "週末", reading: "しゅうまつ", meaning: "weekend" },
              { type: "p", text: "に", reading: "に", meaning: "on" },
              { type: "k", text: "温泉", reading: "おんせん", meaning: "hot spring" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "行きました", reading: "いきました", meaning: "went" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "お湯はとても温かくて、気持ちがよかったです。",
            tokens: [
              { type: "k", text: "お湯", reading: "おゆ", meaning: "hot water" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "plain", text: " とても " },
              { type: "a", text: "温かくて", reading: "あたたかくて", meaning: "warm" },
              { type: "punc", text: "、" },
              { type: "k", text: "気持ち", reading: "きもち", meaning: "feeling" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "a", text: "よかった", reading: "よかった", meaning: "was good" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "山の景色もきれいでした。",
            tokens: [
              { type: "k", text: "山", reading: "やま", meaning: "mountain" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "景色", reading: "けしき", meaning: "scenery" },
              { type: "p", text: "も", reading: "も", meaning: "also" },
              { type: "a", text: "きれい", reading: "きれい", meaning: "beautiful" },
              { type: "v", text: "でした", reading: "でした", meaning: "was" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "We went to a hot spring on the weekend. The water was warm and felt great. The mountain scenery was beautiful.",
        pt: "Fomos a uma fonte termal no fim de semana. A água era morna e nos sentimos muito bem. A paisagem da montanha era linda.",
        es: "Fuimos a unas aguas termales el fin de semana. El agua estaba caliente y se sentía genial. El paisaje de montaña era hermoso.",
      },
    ],
  },
  {
    id: "sushi",
    kanji: "寿司",
    title: "寿司の歴史",
    sub: "The History of Sushi",
    lvl: "N3",
    wm: "寿",
    color: "#e0785a",
    pages: [
      {
        sentences: [
          {
            text: "寿司は日本で最も有名な料理です。",
            tokens: [
              { type: "k", text: "寿司", reading: "すし", meaning: "sushi" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "a", text: "最も", reading: "もっとも", meaning: "most" },
              { type: "a", text: "有名な", reading: "ゆうめいな", meaning: "famous" },
              { type: "k", text: "料理", reading: "りょうり", meaning: "cuisine" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "昔は魚を保存するために米を使いました。",
            tokens: [
              { type: "k", text: "昔", reading: "むかし", meaning: "long ago" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "魚", reading: "さかな", meaning: "fish" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "保存する", reading: "ほぞんする", meaning: "preserve" },
              { type: "plain", text: " ために " },
              { type: "k", text: "米", reading: "こめ", meaning: "rice" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "使いました", reading: "つかいました", meaning: "used" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "今は世界中で愛されています。",
            tokens: [
              { type: "k", text: "今", reading: "いま", meaning: "now" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "世界中", reading: "せかいじゅう", meaning: "worldwide" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "v", text: "愛されています", reading: "あいされています", meaning: "is loved" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Sushi is the most famous cuisine in Japan. Long ago, rice was used to preserve fish. Now it is loved all over the world.",
        pt: "Sushi é a culinária mais famosa do Japão. Antigamente, o arroz era usado para conservar peixe. Agora é amado no mundo inteiro.",
        es: "El sushi es la cocina más famosa de Japón. Hace mucho tiempo, el arroz se usaba para conservar pescado. Ahora es amado en todo el mundo.",
      },
    ],
  },
  {
    id: "matsuri",
    kanji: "祭り",
    title: "夏祭りの夜",
    sub: "A Summer Festival Night",
    lvl: "N4",
    wm: "祭",
    color: "#d45a8a",
    pages: [
      {
        sentences: [
          {
            text: "夏になると、日本中でお祭りがあります。",
            tokens: [
              { type: "k", text: "夏", reading: "なつ", meaning: "summer" },
              { type: "p", text: "に", reading: "に", meaning: "in" },
              { type: "v", text: "なると", reading: "なると", meaning: "when becomes" },
              { type: "punc", text: "、" },
              { type: "k", text: "日本中", reading: "にほんじゅう", meaning: "all Japan" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "plain", text: "お" },
              { type: "k", text: "祭り", reading: "まつり", meaning: "festival" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "あります", reading: "あります", meaning: "exists" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "浴衣を着て、友達と出かけます。",
            tokens: [
              { type: "k", text: "浴衣", reading: "ゆかた", meaning: "yukata" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "着て", reading: "きて", meaning: "wearing" },
              { type: "punc", text: "、" },
              { type: "k", text: "友達", reading: "ともだち", meaning: "friends" },
              { type: "p", text: "と", reading: "と", meaning: "with" },
              { type: "v", text: "出かけます", reading: "でかけます", meaning: "go out" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "花火がとてもきれいです。",
            tokens: [
              { type: "k", text: "花火", reading: "はなび", meaning: "fireworks" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "plain", text: " とても " },
              { type: "a", text: "きれい", reading: "きれい", meaning: "beautiful" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "When summer comes, festivals happen all over Japan. People wear yukata and go out with friends. The fireworks are very beautiful.",
        pt: "Quando o verão chega, festivais acontecem por todo o Japão. As pessoas vestem yukata e saem com amigos. Os fogos de artifício são muito bonitos.",
        es: "Cuando llega el verano, hay festivales por todo Japón. La gente viste yukata y sale con amigos. Los fuegos artificiales son muy hermosos.",
      },
    ],
  },
  {
    id: "ninja",
    kanji: "忍者",
    title: "忍者の秘密",
    sub: "Secrets of the Ninja",
    lvl: "N3",
    wm: "忍",
    color: "#7a7a9a",
    pages: [
      {
        sentences: [
          {
            text: "忍者は日本の歴史で重要な存在でした。",
            tokens: [
              { type: "k", text: "忍者", reading: "にんじゃ", meaning: "ninja" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "歴史", reading: "れきし", meaning: "history" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "a", text: "重要な", reading: "じゅうような", meaning: "important" },
              { type: "k", text: "存在", reading: "そんざい", meaning: "existence" },
              { type: "v", text: "でした", reading: "でした", meaning: "was" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "彼らは暗闇の中で静かに動きました。",
            tokens: [
              { type: "p", text: "彼ら", reading: "かれら", meaning: "they" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "暗闇", reading: "くらやみ", meaning: "darkness" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "中", reading: "なか", meaning: "inside" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "a", text: "静かに", reading: "しずかに", meaning: "quietly" },
              { type: "v", text: "動きました", reading: "うごきました", meaning: "moved" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "特別な武器と技術を使いました。",
            tokens: [
              { type: "a", text: "特別な", reading: "とくべつな", meaning: "special" },
              { type: "k", text: "武器", reading: "ぶき", meaning: "weapons" },
              { type: "p", text: "と", reading: "と", meaning: "and" },
              { type: "k", text: "技術", reading: "ぎじゅつ", meaning: "techniques" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "使いました", reading: "つかいました", meaning: "used" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Ninjas were an important part of Japanese history. They moved silently in the darkness. They used special weapons and techniques.",
        pt: "Os ninjas foram uma parte importante da história japonesa. Eles se moviam silenciosamente na escuridão. Usavam armas e técnicas especiais.",
        es: "Los ninjas fueron una parte importante de la historia japonesa. Se movían en silencio en la oscuridad. Usaban armas y técnicas especiales.",
      },
    ],
  },
  {
    id: "neko",
    kanji: "猫",
    title: "猫カフェの一日",
    sub: "A Day at a Cat Café",
    lvl: "N5",
    wm: "猫",
    color: "#c8a86a",
    pages: [
      {
        sentences: [
          {
            text: "今日は猫カフェに行きました。",
            tokens: [
              { type: "k", text: "今日", reading: "きょう", meaning: "today" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "猫", reading: "ねこ", meaning: "cat" },
              { type: "plain", text: "カフェ" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "行きました", reading: "いきました", meaning: "went" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "猫がたくさんいて、とてもかわいいです。",
            tokens: [
              { type: "k", text: "猫", reading: "ねこ", meaning: "cat" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "plain", text: " たくさん " },
              { type: "v", text: "いて", reading: "いて", meaning: "there are" },
              { type: "punc", text: "、" },
              { type: "plain", text: " とても " },
              { type: "a", text: "かわいい", reading: "かわいい", meaning: "cute" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "一匹の白い猫が私の膝に来ました。",
            tokens: [
              { type: "k", text: "一匹", reading: "いっぴき", meaning: "one animal" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "a", text: "白い", reading: "しろい", meaning: "white" },
              { type: "k", text: "猫", reading: "ねこ", meaning: "cat" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "p", text: "私", reading: "わたし", meaning: "I" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "膝", reading: "ひざ", meaning: "lap" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "来ました", reading: "きました", meaning: "came" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Today I went to a cat café. There were many cats and they were very cute. One white cat came and sat on my lap.",
        pt: "Hoje fui a um cat café. Havia muitos gatos e eram muito fofos. Um gato branco veio e sentou no meu colo.",
        es: "Hoy fui a un cat café. Había muchos gatos y eran muy lindos. Un gato blanco vino y se sentó en mi regazo.",
      },
    ],
  },
  {
    id: "fuji",
    kanji: "富士",
    title: "富士山に登る",
    sub: "Climbing Mount Fuji",
    lvl: "N3",
    wm: "富",
    color: "#5a8aaa",
    pages: [
      {
        sentences: [
          {
            text: "富士山は日本で一番高い山です。",
            tokens: [
              { type: "k", text: "富士山", reading: "ふじさん", meaning: "Mt. Fuji" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "a", text: "一番", reading: "いちばん", meaning: "number one" },
              { type: "a", text: "高い", reading: "たかい", meaning: "tall" },
              { type: "k", text: "山", reading: "やま", meaning: "mountain" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "毎年たくさんの人が登ります。",
            tokens: [
              { type: "k", text: "毎年", reading: "まいとし", meaning: "every year" },
              { type: "plain", text: " たくさん" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "p", text: "人", reading: "ひと", meaning: "people" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "登ります", reading: "のぼります", meaning: "climb" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "頂上からの日の出は素晴らしいです。",
            tokens: [
              { type: "k", text: "頂上", reading: "ちょうじょう", meaning: "summit" },
              { type: "plain", text: "から" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "日の出", reading: "ひので", meaning: "sunrise" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "a", text: "素晴らしい", reading: "すばらしい", meaning: "magnificent" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Mount Fuji is the tallest mountain in Japan. Every year, many people climb it. The sunrise from the summit is magnificent.",
        pt: "O Monte Fuji é a montanha mais alta do Japão. Todo ano, muitas pessoas o escalam. O nascer do sol do cume é magnífico.",
        es: "El Monte Fuji es la montaña más alta de Japón. Cada año, muchas personas lo escalan. El amanecer desde la cumbre es magnífico.",
      },
    ],
  },
  {
    id: "shinkansen",
    kanji: "新幹線",
    title: "新幹線の旅",
    sub: "A Bullet Train Journey",
    lvl: "N2",
    wm: "幹",
    color: "#4a8a6a",
    pages: [
      {
        sentences: [
          {
            text: "新幹線は日本で一番速い電車です。",
            tokens: [
              { type: "k", text: "新幹線", reading: "しんかんせん", meaning: "bullet train" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "a", text: "一番", reading: "いちばん", meaning: "most" },
              { type: "a", text: "速い", reading: "はやい", meaning: "fast" },
              { type: "k", text: "電車", reading: "でんしゃ", meaning: "train" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "東京から大阪まで二時間半で着きます。",
            tokens: [
              { type: "k", text: "東京", reading: "とうきょう", meaning: "Tokyo" },
              { type: "plain", text: "から" },
              { type: "k", text: "大阪", reading: "おおさか", meaning: "Osaka" },
              { type: "plain", text: "まで" },
              { type: "k", text: "二時間半", reading: "にじかんはん", meaning: "2.5 hours" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "v", text: "着きます", reading: "つきます", meaning: "arrives" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "The Shinkansen is the fastest train in Japan. It takes two and a half hours from Tokyo to Osaka.",
        pt: "O Shinkansen é o trem mais rápido do Japão. Leva duas horas e meia de Tóquio a Osaka.",
        es: "El Shinkansen es el tren más rápido de Japón. Tarda dos horas y media de Tokio a Osaka.",
      },
    ],
  },
  {
    id: "tanabata",
    kanji: "七夕",
    title: "七夕の願い",
    sub: "Tanabata Wishes",
    lvl: "N5",
    wm: "星",
    color: "#8a6aaa",
    pages: [
      {
        sentences: [
          {
            text: "七月七日は七夕です。",
            tokens: [
              { type: "k", text: "七月七日", reading: "しちがつなのか", meaning: "July 7th" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "七夕", reading: "たなばた", meaning: "Tanabata" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "短冊に願いを書きます。",
            tokens: [
              { type: "k", text: "短冊", reading: "たんざく", meaning: "paper strip" },
              { type: "p", text: "に", reading: "に", meaning: "on" },
              { type: "k", text: "願い", reading: "ねがい", meaning: "wish" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "書きます", reading: "かきます", meaning: "write" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "星がとてもきれいな夜です。",
            tokens: [
              { type: "k", text: "星", reading: "ほし", meaning: "stars" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "plain", text: " とても " },
              { type: "a", text: "きれいな", reading: "きれいな", meaning: "beautiful" },
              { type: "k", text: "夜", reading: "よる", meaning: "night" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "July 7th is Tanabata. People write wishes on paper strips. It is a night with very beautiful stars.",
        pt: "7 de julho é Tanabata. As pessoas escrevem desejos em tiras de papel. É uma noite com estrelas muito bonitas.",
        es: "El 7 de julio es Tanabata. La gente escribe deseos en tiras de papel. Es una noche con estrellas muy hermosas.",
      },
    ],
  },
  {
    id: "ramen",
    kanji: "拉麺",
    title: "拉麺の世界",
    sub: "The World of Ramen",
    lvl: "N2",
    wm: "麺",
    color: "#d4a04a",
    pages: [
      {
        sentences: [
          {
            text: "日本には色々な拉麺があります。",
            tokens: [
              { type: "k", text: "日本", reading: "にほん", meaning: "Japan" },
              { type: "p", text: "には", reading: "には", meaning: "in" },
              { type: "a", text: "色々な", reading: "いろいろな", meaning: "various" },
              { type: "k", text: "拉麺", reading: "らーめん", meaning: "ramen" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "あります", reading: "あります", meaning: "exists" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "味噌、醤油、塩、豚骨が人気です。",
            tokens: [
              { type: "k", text: "味噌", reading: "みそ", meaning: "miso" },
              { type: "punc", text: "、" },
              { type: "k", text: "醤油", reading: "しょうゆ", meaning: "soy sauce" },
              { type: "punc", text: "、" },
              { type: "k", text: "塩", reading: "しお", meaning: "salt" },
              { type: "punc", text: "、" },
              { type: "k", text: "豚骨", reading: "とんこつ", meaning: "pork bone" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "a", text: "人気", reading: "にんき", meaning: "popular" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "There are many kinds of ramen in Japan. Miso, soy sauce, salt, and pork bone are popular flavors.",
        pt: "Existem muitos tipos de ramen no Japão. Miso, molho de soja, sal e osso de porco são sabores populares.",
        es: "Hay muchos tipos de ramen en Japón. Miso, salsa de soja, sal y hueso de cerdo son sabores populares.",
      },
    ],
  },
  {
    id: "samurai",
    kanji: "侍",
    title: "侍の道",
    sub: "The Way of the Samurai",
    lvl: "N2",
    wm: "刀",
    color: "#aa5a5a",
    pages: [
      {
        sentences: [
          {
            text: "侍は武士道という道徳に従いました。",
            tokens: [
              { type: "k", text: "侍", reading: "さむらい", meaning: "samurai" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "武士道", reading: "ぶしどう", meaning: "bushido" },
              { type: "plain", text: "という" },
              { type: "k", text: "道徳", reading: "どうとく", meaning: "morality" },
              { type: "p", text: "に", reading: "に", meaning: "to" },
              { type: "v", text: "従いました", reading: "したがいました", meaning: "followed" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "名誉と忠義を最も大切にしました。",
            tokens: [
              { type: "k", text: "名誉", reading: "めいよ", meaning: "honor" },
              { type: "p", text: "と", reading: "と", meaning: "and" },
              { type: "k", text: "忠義", reading: "ちゅうぎ", meaning: "loyalty" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "a", text: "最も", reading: "もっとも", meaning: "most" },
              { type: "a", text: "大切に", reading: "たいせつに", meaning: "importantly" },
              { type: "v", text: "しました", reading: "しました", meaning: "did" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Samurai followed a moral code called Bushido. They valued honor and loyalty above all else.",
        pt: "Os samurais seguiam um código moral chamado Bushido. Eles valorizavam a honra e a lealdade acima de tudo.",
        es: "Los samuráis seguían un código moral llamado Bushido. Valoraban el honor y la lealtad por encima de todo.",
      },
    ],
  },
  {
    id: "tea",
    kanji: "茶道",
    title: "茶道の心",
    sub: "The Heart of Tea Ceremony",
    lvl: "N2",
    wm: "茶",
    color: "#6a8a4a",
    pages: [
      {
        sentences: [
          {
            text: "茶道は単なるお茶の飲み方ではありません。",
            tokens: [
              { type: "k", text: "茶道", reading: "さどう", meaning: "tea ceremony" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "a", text: "単なる", reading: "たんなる", meaning: "mere" },
              { type: "plain", text: "お" },
              { type: "k", text: "茶", reading: "ちゃ", meaning: "tea" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "飲み方", reading: "のみかた", meaning: "way of drinking" },
              { type: "plain", text: "では" },
              { type: "v", text: "ありません", reading: "ありません", meaning: "is not" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "和敬清寂という精神が大切です。",
            tokens: [
              { type: "k", text: "和敬清寂", reading: "わけいせいじゃく", meaning: "harmony, respect, purity, tranquility" },
              { type: "plain", text: "という" },
              { type: "k", text: "精神", reading: "せいしん", meaning: "spirit" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "a", text: "大切", reading: "たいせつ", meaning: "important" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Tea ceremony is not merely a way of drinking tea. The spirit of harmony, respect, purity, and tranquility is what matters.",
        pt: "A cerimônia do chá não é apenas uma forma de beber chá. O espírito de harmonia, respeito, pureza e tranquilidade é o que importa.",
        es: "La ceremonia del té no es simplemente una forma de beber té. El espíritu de armonía, respeto, pureza y tranquilidad es lo que importa.",
      },
    ],
  },
  {
    id: "eki",
    kanji: "駅弁",
    title: "駅弁を食べよう",
    sub: "Let's Eat Ekiben!",
    lvl: "N5",
    wm: "弁",
    color: "#e08a4a",
    pages: [
      {
        sentences: [
          {
            text: "電車の中でお弁当を食べます。",
            tokens: [
              { type: "k", text: "電車", reading: "でんしゃ", meaning: "train" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "中", reading: "なか", meaning: "inside" },
              { type: "p", text: "で", reading: "で", meaning: "in" },
              { type: "plain", text: "お" },
              { type: "k", text: "弁当", reading: "べんとう", meaning: "lunchbox" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "食べます", reading: "たべます", meaning: "eat" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "これは駅弁と言います。",
            tokens: [
              { type: "p", text: "これ", reading: "これ", meaning: "this" },
              { type: "p", text: "は", reading: "は", meaning: "topic" },
              { type: "k", text: "駅弁", reading: "えきべん", meaning: "ekiben" },
              { type: "p", text: "と", reading: "と", meaning: "as" },
              { type: "v", text: "言います", reading: "いいます", meaning: "is called" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "とてもおいしいです。",
            tokens: [
              { type: "plain", text: "とても " },
              { type: "a", text: "おいしい", reading: "おいしい", meaning: "delicious" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "You eat lunchboxes on the train. These are called ekiben. They are very delicious.",
        pt: "Você come marmitas no trem. Elas são chamadas de ekiben. São muito deliciosas.",
        es: "Se comen loncheras en el tren. Se llaman ekiben. Son muy deliciosas.",
      },
    ],
  },
  {
    id: "yume",
    kanji: "夢",
    title: "不思議な夢",
    sub: "A Strange Dream",
    lvl: "N3",
    wm: "夢",
    color: "#6a6aaa",
    pages: [
      {
        sentences: [
          {
            text: "昨日、不思議な夢を見ました。",
            tokens: [
              { type: "k", text: "昨日", reading: "きのう", meaning: "yesterday" },
              { type: "punc", text: "、" },
              { type: "a", text: "不思議な", reading: "ふしぎな", meaning: "strange" },
              { type: "k", text: "夢", reading: "ゆめ", meaning: "dream" },
              { type: "p", text: "を", reading: "を", meaning: "object" },
              { type: "v", text: "見ました", reading: "みました", meaning: "saw/had" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "空を飛んで、雲の上を歩きました。",
            tokens: [
              { type: "k", text: "空", reading: "そら", meaning: "sky" },
              { type: "p", text: "を", reading: "を", meaning: "through" },
              { type: "v", text: "飛んで", reading: "とんで", meaning: "flying" },
              { type: "punc", text: "、" },
              { type: "k", text: "雲", reading: "くも", meaning: "clouds" },
              { type: "p", text: "の", reading: "の", meaning: "possessive" },
              { type: "k", text: "上", reading: "うえ", meaning: "above" },
              { type: "p", text: "を", reading: "を", meaning: "on" },
              { type: "v", text: "歩きました", reading: "あるきました", meaning: "walked" },
              { type: "punc", text: "。" },
            ],
          },
          {
            text: "目が覚めたとき、少し悲しかったです。",
            tokens: [
              { type: "k", text: "目", reading: "め", meaning: "eyes" },
              { type: "p", text: "が", reading: "が", meaning: "subject" },
              { type: "v", text: "覚めた", reading: "さめた", meaning: "woke up" },
              { type: "plain", text: "とき" },
              { type: "punc", text: "、" },
              { type: "a", text: "少し", reading: "すこし", meaning: "a little" },
              { type: "a", text: "悲しかった", reading: "かなしかった", meaning: "was sad" },
              { type: "v", text: "です", reading: "です", meaning: "is" },
              { type: "punc", text: "。" },
            ],
          },
        ],
        en: "Yesterday, I had a strange dream. I flew through the sky and walked on the clouds. When I woke up, I felt a little sad.",
        pt: "Ontem, tive um sonho estranho. Voei pelo céu e andei sobre as nuvens. Quando acordei, fiquei um pouco triste.",
        es: "Ayer, tuve un sueño extraño. Volé por el cielo y caminé sobre las nubes. Cuando desperté, me sentí un poco triste.",
      },
    ],
  },
];
